### ISSUE TITLE
DCF radio module or a battery-buffered timer

### ISSUE THREAD

**Issue by JoeBerlin69** [JonnyBooker/split-flap#13]
Hello,
I think the SplitFlap display is great. I've already built several for friends and relatives. Most of them just use the clock. Now I have someone who doesn't have WiFi at home.
Couldn't the electronics be expanded to include a DCF radio module or a battery-buffered timer?
Best wishes
Jörg

**Comment by JonnyBooker** [comment]
Hello!
That is a lot of patience to do it multiple times! 

I'm afraid I don't know much when it comes to the electronics side of it, it might be worth posting that question to the original creator David whom I forked this project from. I can do the software side of it but less so the hardware/electronic side.

Many Thanks

**Comment by JoeBerlin69** [comment]
Hi, i am trying it for myself with a DS3231 Modul. I use the help with ChatGPT and it could work. If possible wr stay in contact during this process and we can help each other. Thanks a lot for your answer.Kind regardsJoergVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Jonny Booker ***@***.***> Datum: 31.05.24  21:15  (GMT+01:00) An: JonnyBooker/split-flap ***@***.***> Cc: JoeBerlin69 ***@***.***>, Author ***@***.***> Betreff: Re: [JonnyBooker/split-flap] DCF radio module or a battery-buffered timer (Issue #13) 
Hello!
That is a lot of patience to do it multiple times!
I'm afraid I don't know much when it comes to the electronics side of it, it might be worth posting that question to the original creator David whom I forked this project from. I can do the software side of it but less so the hardware/electronic side.
Many Thanks

**Comment by JonnyBooker** [comment]
@JoeBerlin69 - Sure, feel free to post here and I'll try answer your questions, no guarantee I can but can try

**Comment by JonnyBooker** [comment]
Not heard anything about this in a while @JoeBerlin69, how is it all going?

**Comment by JonnyBooker** [comment]
Fair enough, no need for sorry! Happy to pick this back up and discuss if you get anymore time to work on it in future! I'll close this issue for now but happy to re-open it if need be
