### ISSUE TITLE
wifi control

### ISSUE THREAD

**Issue by j-gaikwad** [JonnyBooker/split-flap#8]
I'm having an issue with the ESP8266 actually controlling the unit.  The unit is working correctly via test mode and I can access the UI on the ESP just fine. When I hook up a serial debugger to the ESP here is what i'm seeing in the output.

I have UNITS_AMOUNT set to 2 as that's all I have built and connected for testing.  

Try to wake up unit
A unit in the display is sleeping
Waiting for a display to stop
0:-1

Thanks!

**Comment by j-gaikwad** [comment]
all good here, needed to disable serial

**Comment by JonnyBooker** [comment]
Fallen for that one myself before. Glad got it sorted @j-gaikwad!
